### ISSUE TITLE
Colors and text not getting restored properly

### ISSUE THREAD

**Issue by rashil2000** [nightroman/PS-GuiCompletion#5]
Have a look at this GIF:

![Animation](https://user-images.githubusercontent.com/46838874/119779943-daf24c80-bee6-11eb-8c04-7b226a5090d0.gif)

The (24-bit) colors and text properties (bold, italics etc.) do not get restored fully after the GuiCompletion menu is closed. Of course this happens only when the menu opens up above the current line (because there's no space below).

This happens on both Windows PowerShell and PowerShell Core, and all terminals I have tested (conhost, VSCode, Windows Terminal, mintty).

**Comment by rashil2000** [comment]
I don't know about the underlying logic much, but a hacky workaround can be forcing the terminal to scroll down (like how PSReadline does) so that the menu always appears below the current line (and a flag in $GuiCompletionConfig to control this behaviour).

**Comment by nightroman** [comment]
Thank you for the detailed report and the original suggested workaround.

After some trial and errors I have got something working reasonably well.

Some notes:

- The promising PSReadLine `ScrollDisplayDownLine` does not work if the caret is at the bottom of the buffer.
- Thus, the scrolling is forced instead by inserting several new lines and undoing this change.

The new mode is optional, it is enabled by:

    $GuiCompletionConfig.ScrollDisplayDown = $true

Please let me know how it all goes with just pushed v0.11.0.
I do not use "advanced" consoles in order to properly test this.

P.S. I rather like this mode. If it works fine we may enable it by default, so that users do not have to work around issues.

**Comment by rashil2000** [comment]
Thanks for such a quick fix! It works great!

However, if you don't mind, I have a question. Was it not possible to restore all the colors/text properties properly, as opposed to this workaround? I'd completely understand if scrolling down was the only possible way to fix this.

Thanks again!

**Comment by nightroman** [comment]
> Was it not possible to restore all the colors/text properties properly, as opposed to this workaround?

That is probably the question or bug report to the PowerShell team :) GuiCompletion just uses `$Host.UI.RawUI` `GetBufferContents` and `SetBufferContents`.

**Comment by rashil2000** [comment]
Oh, okay, do you reckon I open an issue in their repo, referencing your comment here?

**Comment by nightroman** [comment]
Up to you totally.

**Comment by nightroman** [comment]
@rashil2000 FYI, in v0.11.1 this feature is on by default.

**Comment by rashil2000** [comment]
Great, thanks for the update!
